# Generated by Django 5.0.6 on 2024-07-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tennis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='Tennis.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('regular', 'regular'), ('admin', 'admin')], max_length=50, unique=True),
        ),
    ]
