# Generated by Django 5.0.6 on 2024-07-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tennis', '0002_alter_customuser_role_alter_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Tennis game', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='Tennis.role'),
        ),
    ]
