# Generated by Django 5.0.6 on 2024-07-23 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tennis', '0003_game_name_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='Tennis.role'),
        ),
    ]
