# Generated by Django 5.0.6 on 2024-07-23 14:20

import Tennis.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tennis', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=Tennis.models.Role.get_default_role, on_delete=django.db.models.deletion.CASCADE, to='Tennis.role'),
        ),
    ]
